%YAML:1.0

# ORB-SLAM3 Configuration for Jetson Xavier NX
# Optimized for low power consumption and real-time performance

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
# Optimized for 320x240 resolution on Jetson
Camera.fx: 307.695
Camera.fy: 307.695
Camera.cx: 160.0
Camera.cy: 120.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

# Reduced resolution for Jetson performance
Camera.width: 320
Camera.height: 240

# Reduced FPS for power efficiency
Camera.fps: 15.0

# IR projector baseline times fx (aprox.)
Camera.bf: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 20.0

# Depthmap values factor 
DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Extractor: Reduced features for Jetson performance
ORBextractor.nFeatures: 500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Reduced levels for performance
ORBextractor.nLevels: 6

# ORB Extractor: Fast threshold
# Optimized for Jetson performance
ORBextractor.iniThFAST: 25
ORBextractor.minThFAST: 10

#--------------------------------------------------------------------------------------------
# Viewer Parameters (disabled for Jetson)
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

#--------------------------------------------------------------------------------------------
# System parameters optimized for Jetson Xavier NX
System.thFarPoints: 15.0
System.LoadMap: false
System.SaveMap: false

# Tracking parameters for low power consumption
Tracking.LocalMapSize: 40
Tracking.KeyFrameSize: 10

# Loop closing optimizations
LoopClosing.MinMatches: 20
LoopClosing.ConsistentMatches: 3

# Local mapping optimizations  
LocalMapping.MaxKeyFrames: 50
LocalMapping.RedundantThreshold: 0.9

#--------------------------------------------------------------------------------------------
# Multi-session parameters (disabled for single session use)
Atlas.SavePath: ""
Atlas.LoadPath: ""

#--------------------------------------------------------------------------------------------
# IMU Parameters (if using IMU sensor)
IMU.NoiseGyro: 1.7e-4
IMU.NoiseAcc: 2.0e-3
IMU.GyroWalk: 1.9e-5
IMU.AccWalk: 3.0e-3
IMU.Frequency: 200
IMU.Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
          0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
          -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
          0.0, 0.0, 0.0, 1.0]
